name: platzi_trips
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^1.10.5
  firebase_analytics: ^5.0.2
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  image_picker: ^0.8.4+11
  image: ^3.1.3
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  generic_bloc_provider: ^2.1.1
  google_sign_in: ^5.2.4
  firebase_storage: ^10.2.3
  firebase_crashlytics: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/foto_anibal.jpg
    - assets/img/paisaje1.jpg
    - assets/img/paisaje2.jpg
    - assets/img/paisaje3.jpg
    - assets/img/paisaje4.png
    - assets/img/paisaje5.jpg
    - assets/img/paisaje6.jpg
    - assets/img/paisaje7.jpg
    - assets/img/selfie1.jpg
    - assets/img/selfie2.jpg
    - assets/img/selfie3.png
    - assets/img/selfie4.png
    - assets/img/selfie5.jpg
    - assets/img/paisaje6.jpg
    - assets/img/people.jpg
    - assets/img/ann.jpg
    - assets/img/girl.jpg
    - assets/img/mountain.jpeg
    - assets/img/beach.jpeg
    - assets/img/beach_palm.jpeg
    - assets/img/mountain_stars.jpeg
    - assets/img/sunset.jpeg
    - assets/img/river.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fuentes/Lato-Regular.ttf
